### PR TITLE
Sanitaiton & Clean Up.

### PR DESCRIPTION
**Pull request by DiscoRiver**
Some comment sanitation and code clean up for your good repo!

### CODE REVIEW

**Comment by pratikbin** [comment]
@aman00323 or @Naman2706  Any updates on this ?

**Comment by aman00323** [comment]
@pratikbin Looks good can anyone test this locally @Naman2706, @pratikbin, @vyas-shyam

**Comment by DiscoRiver** [comment]
Following up to get this one closed out.

**Review by vyas-shyam — APPROVED** [review]

**Review by pratikbin — APPROVED** [review]

**Comment by pratikbin** [comment]
@DiscoRiver GitHub facing some issue in CI approvals, so I'll lint and scan code in local and will merge if everything goes fine

**Comment by pratikbin** [comment]
@DiscoRiver Thank you for contribution. Hope it help(s|d) you. 

> May the source be with you

**Pull request merged**
